name = "binance-proxy"
main = "index.js"
compatibility_date = "2025-11-15"
account_id = "87950afe1868fd206de9c7dc65fbca3c"

[vars]
BINANCE_UPSTREAM = "https://fapi.binance.com"
# Set BINANCE_PROXY_KEY via `wrangler secret put BINANCE_PROXY_KEY`
